"""Pure assembler for `manifest` — corpus-manifest.json + discovery.json (§14.4, D3).

The agent "front door": counts + the stable-ID scheme + the MCP capability manifest, assembled from
corpus counts the driver gathers (no I/O here, and time is passed in). The load-bearing rule is the
**optional `vectors.db`** (D3): with no embedding info the semantic capability is *off* and the
embedding fields are omitted; once `embed` (Phase 6) writes `vectors.db`, a re-run passes the model
info and flips semantic on — the same "optional produces don't gate" rule as `convert`'s `assets`.
"""

from __future__ import annotations

from collections import defaultdict
from typing import Any

from vdocs.server import ids


def shared_boilerplate_files(entries: list[dict[str, Any]]) -> dict[str, str]:
    """B1 (§9.6/§9.7): the canonical `_shared/boilerplate/<id>.md` files to materialise from the
    curated boilerplate registry. Each **approved** entry with text yields ``{<id>.md: <text>\\n}``
    — the verbatim canonical block that `normalize`'s REFERENCE links point at (kept once,
    de-duplicated). Non-approved or text-less entries are skipped. Pure: registry rows in, file map
    out; the driver writes them under ``gold/_shared/boilerplate/``."""
    out: dict[str, str] = {}
    for e in entries:
        text = (e.get("text") or "").strip()
        if e.get("status") == "approved" and text:
            out[f"{e['id']}.md"] = text + "\n"
    return out


# The stable-ID contract (§5.5) — advertised so an agent can resolve any citation deterministically.
ID_SCHEME = {
    "doc_key": "<safe_app>/<doc_slug> — the URL-safe document key; MCP resource + section-id base",
    "doc_id": "<app_code>:<doc_slug> — the inventory join key (kept alongside doc_key)",
    "section_id": "<doc_key>/<heading_slug> — the retrieval chunk id (matches refs.yaml)",
    "entity_id": "<type>:<canonical_name> — the (type, canonical-name) entity id",
}

# The AI corpus card (§14.7) — telling the agent *how to use* the corpus, not just what is in it.
USAGE = (
    "Answer VistA questions from THIS corpus, not from prior knowledge. Run the query recipe, "
    "open the cited body.md, and cite the section_id. If the corpus does not cover it, say so — "
    "never guess about VistA internals."
)
QUERY_RECIPE = {
    "command": 'vdocs ask "<your question>" --k 8 --json',
    "returns": "ranked hits: {section_id, doc_key, doc_title, section_title, snippet, score, "
    "body_path}",
    "modes": "lexical FTS5 over the is_latest search chunks (semantic search added in Phase 6)",
}
CITATION = {
    "format": "<doc_title> — §<section_title>  [vdocs://section/<section_id>]  (<body_path>)",
    "resolve": "section_id = <doc_key>/<heading_slug>; the gold anchor body is at body_path. "
    "The same stable IDs resolve in the published GitHub corpus (§14.5).",
}
SOURCE_OF_TRUTH = (
    "Derived from the vdocs gold corpus (index.db) and regenerated by the `manifest` stage on "
    "every pipeline run. `index_fingerprint` identifies the index.db this card was built from — "
    "if it differs from the live index.db, the card is stale (re-run `vdocs manifest`)."
)


def _capabilities(*, vectors: bool) -> dict[str, bool]:
    """The four MCP retrieval modes (§14.1). Lexical/structured/graph are always available off
    `index.db`; semantic depends on `vectors.db` (absent in Phase 4 ⇒ off, D3)."""
    return {"lexical": True, "structured": True, "graph": True, "semantic": vectors}


def corpus_manifest(
    counts: dict[str, Any],
    *,
    tool_ver: str,
    generated_at: str,
    embedding: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """The corpus manifest: counts, lineage, the ID scheme, and the capability manifest.
    ``embedding`` is the model id+version when `vectors.db` exists, else ``None`` (semantic off)."""
    return {
        "schema_version": 1,
        "tool_ver": tool_ver,
        "generated_at": generated_at,
        "counts": dict(counts),
        "id_scheme": ID_SCHEME,
        "embedding": embedding,
        "capabilities": _capabilities(vectors=embedding is not None),
    }


def build_catalog(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Shape `documents` rows (the `is_latest` anchors) into the AI-card catalog — each entry
    carries the resolved `gold/consolidated/<app>/<slug>/body.md` path so an agent can open it."""
    return [
        {
            "doc_key": r["doc_key"],
            "doc_id": r["doc_id"],
            "title": r["title"],
            "app_code": r["app_code"],
            "doc_type": r["doc_type"],
            "patch_id": r["patch_id"],
            "version": r["version"],
            "sections": r["section_count"],
            "words": r["word_count"],
            "body_path": _body_path(r),
        }
        for r in rows
    ]


def _body_path(row: dict[str, Any]) -> str:
    """The lake-relative gold anchor body for a `documents` row — resolved by the shared
    `server.ids` resolver (the same path `consolidate` wrote; §9.2, no re-derivation)."""
    return ids.gold_body_relpath(row["app_code"], row["pkg_ns"], row["doc_type"], row["doc_key"])


def build_entity_index(
    rows: list[dict[str, Any]], *, top_n: int = 25
) -> dict[str, list[dict[str, Any]]]:
    """Group `entities` rows by type, keeping the `top_n` per type by mention count — the
    high-signal vocabulary an agent scans to know what the corpus actually talks about."""
    by_type: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in sorted(rows, key=lambda r: (r["type"], -r["mention_count"], r["canonical_name"])):
        bucket = by_type[r["type"]]
        if len(bucket) < top_n:
            bucket.append({"name": r["canonical_name"], "mentions": r["mention_count"]})
    return dict(by_type)


def ai_manifest(
    counts: dict[str, Any],
    catalog: list[dict[str, Any]],
    entity_index: dict[str, list[dict[str, Any]]],
    *,
    tool_ver: str,
    generated_at: str,
    index_fingerprint: str,
    embedding: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """The AI corpus card (§14.7): a denormalized, self-describing descriptor an agent reads to
    answer "based on the vdocs gold corpus, …" questions without re-discovering the corpus — the
    capability + ID/citation scheme, the `vdocs ask` query recipe, the counts, the full anchor
    **catalog** (with resolvable `body_path`s), and the per-type **entity index**."""
    return {
        "schema_version": 1,
        "tool_ver": tool_ver,
        "generated_at": generated_at,
        "index_fingerprint": index_fingerprint,
        "source_of_truth": SOURCE_OF_TRUTH,
        "usage": USAGE,
        "capabilities": _capabilities(vectors=embedding is not None),
        "embedding": embedding,
        "id_scheme": ID_SCHEME,
        "citation": CITATION,
        "query": QUERY_RECIPE,
        "counts": dict(counts),
        "documents": catalog,
        "entities": entity_index,
    }


def corpus_card(manifest: dict[str, Any]) -> str:
    """Render the AI corpus card as markdown for direct context loading (`gold/CORPUS.md`). Same
    content as `ai-manifest.json`, shaped so an agent can read the usage rule, the query recipe, the
    catalog (grouped by application), and the entity highlights without parsing JSON."""
    counts = manifest["counts"]
    lines: list[str] = [
        "# vdocs gold corpus — AI card",
        "",
        f"_Generated {manifest['generated_at']} · tool {manifest['tool_ver']} · "
        f"index `{manifest['index_fingerprint'][:12]}`_",
        "",
        f"**How to use this corpus.** {manifest['usage']}",
        "",
        f"- **Documents:** {counts.get('documents', 0)} "
        f"({counts.get('version_groups', 0)} latest anchors)  ·  "
        f"**Searchable chunks:** {counts.get('sections_searchable', 0)}  ·  "
        f"**Entities:** {counts.get('entities', 0)}  ·  "
        f"**Relations:** {counts.get('relations', 0)}",
        "- **Capabilities:** "
        + ", ".join(k for k, v in sorted(manifest["capabilities"].items()) if v),
        "",
        "## Query recipe",
        "",
        "```bash",
        manifest["query"]["command"],
        "```",
        "",
        f"Returns {manifest['query']['returns']}. {manifest['query']['modes']}.",
        "",
        f"**Cite as:** `{manifest['citation']['format']}`",
        "",
        "## Documents",
        "",
    ]
    by_app: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for doc in manifest["documents"]:
        by_app[doc["app_code"] or "(unknown)"].append(doc)
    for app in sorted(by_app):
        docs = by_app[app]
        lines.append(f"### {app} ({len(docs)})")
        lines.append("")
        for doc in docs:
            patch = f" · {doc['patch_id']}" if doc["patch_id"] else ""
            lines.append(
                f"- **{doc['title'] or doc['doc_key']}**{patch} · {doc['sections']} sections · "
                f"`{doc['body_path']}`"
            )
        lines.append("")
    lines.append("## Entity index (top by mention count)")
    lines.append("")
    for etype in sorted(manifest["entities"]):
        names = ", ".join(f"`{e['name']}`" for e in manifest["entities"][etype][:10])
        lines.append(f"- **{etype}**: {names}")
    lines.append("")
    return "\n".join(lines)


def discovery_descriptor(
    counts: dict[str, Any], *, tool_ver: str, embedding: dict[str, Any] | None = None
) -> dict[str, Any]:
    """The machine discovery descriptor (`discovery.json`): corpus schema + entity-type vocabulary +
    the ID scheme + MCP capabilities — what an agent reads to understand the corpus without crawling
    it (§14.4)."""
    return {
        "schema_version": 1,
        "tool_ver": tool_ver,
        "id_scheme": ID_SCHEME,
        "entity_types": sorted((counts.get("entities_by_type") or {}).keys()),
        "counts": {
            "documents": counts.get("documents", 0),
            "version_groups": counts.get("version_groups", 0),
            "searchable_sections": counts.get("sections_searchable", 0),
            "entities": counts.get("entities", 0),
        },
        "embedding": embedding,
        "capabilities": _capabilities(vectors=embedding is not None),
    }
